# -*- coding: utf-8 -*-
"""vector_setup.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsFrvbMvJ999kCLU-wHor3vVUYC1WKcZ
"""

!pip install chromadb -q --upgrade

reliance_text = """Reliance Industries reported consolidated revenue of ₹2,45,000 crore for Q2 FY26, up 8.2% year-on-year, driven primarily by growth in the retail and digital services segments. EBITDA margin improved to 17.3%..."""

hdfc_text = """HDFC Bank reported net interest income of ₹30,200 crore for Q2 FY26, up 9.4% year-on-year..."""

zomato_text = """Zomato reported consolidated revenue of ₹4,850 crore for Q2 FY26, up 14.7% quarter-on-quarter..."""

reliance_text="""Reliance Industries Limited – Q2 FY26 Earnings Summary

Reliance Industries reported consolidated revenue of ₹2,45,000 crore for
Q2 FY26, up 8.2% year-on-year, driven primarily by growth in the retail
and digital services segments. EBITDA margin improved to 17.3%, compared
to 16.1% in the same quarter last year.

The company's debt-to-equity ratio stood at 0.35, down from 0.41,
reflecting continued deleveraging efforts. Capital expenditure for the
quarter was ₹18,200 crore, largely directed toward renewable energy
infrastructure and 5G network expansion.

Management highlighted risks including volatility in crude oil prices
and regulatory uncertainty in the telecom tariff structure, but
expressed confidence in double-digit revenue growth for the full
fiscal year."""

hdfc_text="""HDFC Bank Limited – Q2 FY26 Earnings Summary

HDFC Bank reported net interest income of ₹30,200 crore for Q2 FY26,
up 9.4% year-on-year, driven by steady growth in retail and SME loan
disbursements. Gross non-performing assets (NPA) ratio stood at 1.3%,
broadly stable compared to the previous quarter.

The bank's capital adequacy ratio improved to 18.6%, well above
regulatory requirements, following continued balance sheet
consolidation post-merger. Deposit growth was recorded at 11.2%
year-on-year, with a healthy mix of low-cost current and savings
account (CASA) deposits.

Management flagged margin pressure from rising deposit costs but
expressed confidence in sustained loan book growth, particularly in
the unsecured retail and MSME lending segments."""

zomato_text="""Zomato Limited – Q2 FY26 Earnings Summary

Zomato reported consolidated revenue of ₹4,850 crore for Q2 FY26, up
14.7% quarter-on-quarter, driven primarily by growth in its quick
commerce segment, Blinkit. Adjusted EBITDA margin narrowed to 1.2%,
down from 2.8% in the prior quarter, due to aggressive investment in
dark store expansion.

The company added 120 new Blinkit dark stores during the quarter,
while food delivery gross order value grew 9.3% year-on-year. Customer
acquisition costs rose amid intensifying competition in the quick
commerce space.

Management indicated that profitability in the food delivery segment
remains stable, while Blinkit is expected to reach breakeven within
the next two to three quarters, contingent on continued scale-driven
efficiency gains."""

import chromadb

client = chromadb.Client()
collection = client.create_collection("filings")

collection.add(
    documents=[reliance_text, hdfc_text, zomato_text],
    ids=["reliance_filing", "hdfc_filing", "zomato_filing"],
    metadatas=[
        {"company": "Reliance"},
        {"company": "HDFC Bank"},
        {"company": "Zomato"}
    ]
)

print("Documents loaded into vector database")

results = collection.query(
    query_texts=["What is the company's debt situation?"],
    n_results=1
)
print(results)