# -*- coding: utf-8 -*-
"""finalapp(4)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YnYXhRch8nvZrtGC1_bfeh3QiUxYbs4
"""



"""### Switch from `google.generativeai` to `google.genai`

As indicated by the warning, the `google.generativeai` package is deprecated. We will switch to `google.genai`.

First, we uninstall the old package and install the new one. Then, we'll configure the API key.

**Note**: If you haven't already, please store your Google API Key in Colab's Secrets Manager (click the 🔑 icon in the left panel) under the name `GOOGLE_API_KEY`.
"""

# Ensure google-generativeai is installed (it provides GenerativeModel)
pip install google-generativeai -q

import google.generativeai as genai
from google.colab import userdata

# Configure the API key using Colab secrets
GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

# Initialize the model using the new package and the 'gemini-3.6-flash' model
model = genai.GenerativeModel("gemini-3.6-flash")

import google.generativeai as genai

genai.configure(api_key="AQ.Ab8RN6IwksWMYn-bXogojAsQwk7JnVLfsYJGRqR85oKUmYhfhQ")
model = genai.GenerativeModel("gemini-3.5-flash-lite")

# -*- coding: utf-8 -*-
"""vector_setup.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsFrvbMvJ999kCLU-wHor3vVUYC1WKcZ
"""

!pip install chromadb -q --upgrade

reliance_text = """Reliance Industries reported consolidated revenue of ₹2,45,000 crore for Q2 FY26, up 8.2% year-on-year, driven primarily by growth in the retail and digital services segments. EBITDA margin improved to 17.3%..."""

hdfc_text = """HDFC Bank reported net interest income of ₹30,200 crore for Q2 FY26, up 9.4% year-on-year..."""

zomato_text = """Zomato reported consolidated revenue of ₹4,850 crore for Q2 FY26, up 14.7% quarter-on-quarter..."""

reliance_text="""Reliance Industries Limited – Q2 FY26 Earnings Summary

Reliance Industries reported consolidated revenue of ₹2,45,000 crore for
Q2 FY26, up 8.2% year-on-year, driven primarily by growth in the retail
and digital services segments. EBITDA margin improved to 17.3%, compared
to 16.1% in the same quarter last year.

The company's debt-to-equity ratio stood at 0.35, down from 0.41,
reflecting continued deleveraging efforts. Capital expenditure for the
quarter was ₹18,200 crore, largely directed toward renewable energy
infrastructure and 5G network expansion.

Management highlighted risks including volatility in crude oil prices
and regulatory uncertainty in the telecom tariff structure, but
expressed confidence in double-digit revenue growth for the full
fiscal year."""

hdfc_text="""HDFC Bank Limited – Q2 FY26 Earnings Summary

HDFC Bank reported net interest income of ₹30,200 crore for Q2 FY26,
up 9.4% year-on-year, driven by steady growth in retail and SME loan
disbursements. Gross non-performing assets (NPA) ratio stood at 1.3%,
broadly stable compared to the previous quarter.

The bank's capital adequacy ratio improved to 18.6%, well above
regulatory requirements, following continued balance sheet
consolidation post-merger. Deposit growth was recorded at 11.2%
year-on-year, with a healthy mix of low-cost current and savings
account (CASA) deposits.

Management flagged margin pressure from rising deposit costs but
expressed confidence in sustained loan book growth, particularly in
the unsecured retail and MSME lending segments."""

zomato_text="""Zomato Limited – Q2 FY26 Earnings Summary

Zomato reported consolidated revenue of ₹4,850 crore for Q2 FY26, up
14.7% quarter-on-quarter, driven primarily by growth in its quick
commerce segment, Blinkit. Adjusted EBITDA margin narrowed to 1.2%,
down from 2.8% in the prior quarter, due to aggressive investment in
dark store expansion.

The company added 120 new Blinkit dark stores during the quarter,
while food delivery gross order value grew 9.3% year-on-year. Customer
acquisition costs rose amid intensifying competition in the quick
commerce space.

Management indicated that profitability in the food delivery segment
remains stable, while Blinkit is expected to reach breakeven within
the next two to three quarters, contingent on continued scale-driven
efficiency gains."""

import chromadb

client = chromadb.Client()
collection = client.get_or_create_collection("filings")

collection.add(
    documents=[reliance_text, hdfc_text, zomato_text],
    ids=["reliance_filing", "hdfc_filing", "zomato_filing"],
    metadatas=[
        {"company": "Reliance"},
        {"company": "HDFC Bank"},
        {"company": "Zomato"}
    ]
)

print("Documents loaded into vector database")

results = collection.query(
    query_texts=["What is the company's debt situation?"],
    n_results=1
)
print(results)

def rag_agent(stock_name, query):
    results = collection.query(query_texts=[query], n_results=1)
    retrieved_text = results['documents'][0][0]

    prompt = f"""You are a fundamentals research agent. Based on this filing excerpt:
{retrieved_text}

Answer: {query}
Return ONLY JSON: {{"agent": "rag", "signal": "bullish/bearish/neutral", "confidence": 0-1, "reasoning": "1-2 sentences citing the filing", "source_snippet": "short quote"}}"""
    try:
      response = model.generate_content(prompt)
      return response.text
    except Exception as e:
      print("generate_content failed:",e)
      raise

print(rag_agent("Reliance", "How is Reliance's debt and financial health?"))

import re
response_text_from_agent = rag_agent("Reliance", "How is Reliance's debt and financial health?")
clean_text = re.sub(r"```json|```", "", response_text_from_agent).strip()

def synthesis_agent(momentum_out, sentiment_out, rag_out, user_risk_profile):
    prompt = f"""You are the final decision-making agent. You've received 3 independent analyses:

MOMENTUM AGENT: {momentum_out}
SENTIMENT AGENT: {sentiment_out}
RAG AGENT: {rag_out}

User's risk profile: {user_risk_profile}

First, identify if any agents DISAGREE with each other (different signals).
Then explain how you're resolving the disagreement and why, considering the user's risk profile.

Return ONLY JSON:
{{
  "agents_agree": true/false,
  "conflict_summary": "describe any disagreement in 1-2 sentences, or 'No conflict' if none",
  "final_signal": "bullish/bearish/neutral",
  "final_confidence": 0-1,
  "resolution_reasoning": "explain how you weighed conflicting signals for THIS user's risk profile"
"""

    response = model.generate_content(prompt)
    return response.text

fake_momentum = '{"agent": "momentum", "signal": "bullish", "confidence": 0.8, "reasoning": "Price up 5% above MA20 with strong volume"}'
fake_sentiment = '{"agent": "sentiment", "signal": "bearish", "confidence": 0.7, "reasoning": "Recent headlines flag margin pressure and rising competition"}'
fake_rag = '{"agent": "rag", "signal": "neutral", "confidence": 0.6, "reasoning": "Filing shows stable revenue growth but rising costs", "source_snippet": "revenue grew 14.7% but EBITDA margin narrowed"}'

result = synthesis_agent(fake_momentum, fake_sentiment, fake_rag, "aggressive")
print(result)

import re, json

def clean_json_response(text):
    cleaned = re.sub(r"```json|```", "", text).strip()
    try:
        return json.loads(cleaned)
    except:
        return {"error": "Could not parse", "raw": cleaned}

result_dict = clean_json_response(result)
print(result_dict)

# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6LLyO5kVerXepu0Dn205-maygrOUoe5
"""

import os
!pip install groq

from groq import Groq

# Ensure the API key is loaded securely, e.g., from environment variables
client = Groq(api_key=os.environ.get("GROQ_API_KEY", "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"))

def momentum_agent(stock_name, price_summary):
    prompt = f"""You are a technical analysis agent. Stock: {stock_name}
Price data: {price_summary}

Return ONLY JSON: {{\"agent\": \"momentum\", \"signal\": \"bullish/bearish/neutral\", \"confidence\": 0-1, \"reasoning\": \"1-2 sentences\"}}"""

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b", # Changed model from 'llama2-70b-4096' to 'mixtral-8x7b-32768'
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

print(momentum_agent("Reliance", "Price up 4% over 20 days, above MA20, rising volume"))

def sentiment_agent(stock_name, headlines):
    prompt = f"""You are a news sentiment agent. Stock: {stock_name}
Headlines: {headlines}

Return ONLY JSON: {{"agent": "sentiment", "signal": "bullish/bearish/neutral", "confidence": 0-1, "reasoning": "1-2 sentences"}}"""

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

print(sentiment_agent("Zomato", "Zomato's Blinkit drives strong quarterly revenue growth; Zomato margins narrow as quick commerce expansion accelerates"))

m = momentum_agent("Reliance", "Price up 4% over 20 days, above MA20, rising volume")
s = sentiment_agent("Reliance", "Reliance Q2 profit beats estimates; Reliance faces scrutiny over telecom tariff hike")
r = rag_agent("Reliance", "How is Reliance's financial health?")
final = synthesis_agent(m, s, r, "aggressive")

print("MOMENTUM:", m)
print("SENTIMENT:", s)
print("RAG:", r)
print("FINAL:", final)

from google.colab import userdata
userdata.get('GOOGLE_API_KEY')