# -*- coding: utf-8 -*-
"""final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udLmLANjWOdqIvk4ciNf7sDT7btZwjKX
"""

!pip install google-generativeai -q

import google.generativeai as genai

genai.configure(api_key="AQ.Ab8RN6KMXNZACW3gNViiFz-xyyBgzSmD3-Pzw_QQ0QPSWyGhrA")
model = genai.GenerativeModel("gemini-3.6-flash")

import chromadb

client_db = chromadb.Client()

# Attempt to delete the collection if it already exists, to ensure a clean state
try:
    client_db.delete_collection("filings")
except:
    pass # Collection doesn't exist, no need to delete

collection = client_db.get_or_create_collection("filings")

reliance_text = """Reliance Industries Limited – Q2 FY26 Earnings Summary

Reliance Industries reported consolidated revenue of ₹2,45,000 crore for
Q2 FY26, up 8.2% year-on-year, driven primarily by growth in the retail
and digital services segments. EBITDA margin improved to 17.3%, compared
to 16.1% in the same quarter last year.

The company's debt-to-equity ratio stood at 0.35, down from 0.41,
reflecting continued deleveraging efforts. Capital expenditure for the
quarter was ₹18,200 crore, largely directed toward renewable energy
infrastructure and 5G network expansion.

Management highlighted risks including volatility in crude oil prices
and regulatory uncertainty in the telecom tariff structure, but
expressed confidence in double-digit revenue growth for the full
fiscal year."""
hdfc_text = """HDFC Bank Limited – Q2 FY26 Earnings Summary

HDFC Bank reported net interest income of ₹30,200 crore for Q2 FY26,
up 9.4% year-on-year, driven by steady growth in retail and SME loan
disbursements. Gross non-performing assets (NPA) ratio stood at 1.3%,
broadly stable compared to the previous quarter.

The bank's capital adequacy ratio improved to 18.6%, well above
regulatory requirements, following continued balance sheet
consolidation post-merger. Deposit growth was recorded at 11.2%
year-on-year, with a healthy mix of low-cost current and savings
account (CASA) deposits.

Management flagged margin pressure from rising deposit costs but
expressed confidence in sustained loan book growth, particularly in
the unsecured retail and MSME lending segments."""
zomato_text = """Zomato Limited – Q2 FY26 Earnings Summary

Zomato reported consolidated revenue of ₹4,850 crore for Q2 FY26, up
14.7% quarter-on-quarter, driven primarily by growth in its quick
commerce segment, Blinkit. Adjusted EBITDA margin narrowed to 1.2%,
down from 2.8% in the prior quarter, due to aggressive investment in
dark store expansion.

The company added 120 new Blinkit dark stores during the quarter,
while food delivery gross order value grew 9.3% year-on-year. Customer
acquisition costs rose amid intensifying competition in the quick
commerce space.

Management indicated that profitability in the food delivery segment
remains stable, while Blinkit is expected to reach breakeven within
the next two to three quarters, contingent on continued scale-driven
efficiency gains."""

collection.add(
    documents=[reliance_text, hdfc_text, zomato_text],
    ids=["reliance_filing", "hdfc_filing", "zomato_filing"],
    metadatas=[{"company": "Reliance"}, {"company": "HDFC Bank"}, {"company": "Zomato"}]
)
print("Vector DB ready")

def rag_agent(stock_name, query):
    results = collection.query(query_texts=[query], n_results=1)
    retrieved_text = results['documents'][0][0]

    prompt = f"""You are a fundamentals research agent. Based on this filing excerpt:
{retrieved_text}

Answer: {query}
Return ONLY JSON: {{"agent": "rag", "signal": "bullish/bearish/neutral", "confidence": 0-1, "reasoning": "1-2 sentences citing the filing", "source_snippet": "short quote"}}"""

    response = model.generate_content(prompt)
    return response.text

print(rag_agent("Reliance", "How is Reliance's debt and financial health?"))

import re
response_text_from_agent = rag_agent("Reliance", "How is Reliance's debt and financial health?")
clean_text = re.sub(r"```json|```", "", response_text_from_agent).strip()

def synthesis_agent(momentum_out, sentiment_out, rag_out, user_risk_profile):
    prompt = f"""You are the final decision-making agent. You've received 3 independent analyses:

MOMENTUM AGENT: {momentum_out}
SENTIMENT AGENT: {sentiment_out}
RAG AGENT: {rag_out}

User's risk profile: {user_risk_profile}

First, identify if any agents DISAGREE with each other (different signals).
Then explain how you're resolving the disagreement and why, considering the user's risk profile.

Return ONLY JSON:
{{
  "agents_agree": true/false,
  "conflict_summary": "describe any disagreement in 1-2 sentences, or 'No conflict' if none",
  "final_signal": "bullish/bearish/neutral",
  "final_confidence": 0-1,
  "resolution_reasoning": "explain how you weighed conflicting signals for THIS user's risk profile"
}}"""

    response = model.generate_content(prompt)
    return response.text

fake_momentum = '{"agent": "momentum", "signal": "bullish", "confidence": 0.8, "reasoning": "Price up 5% above MA20 with strong volume"}'
fake_sentiment = '{"agent": "sentiment", "signal": "bearish", "confidence": 0.7, "reasoning": "Recent headlines flag margin pressure and rising competition"}'
fake_rag = '{"agent": "rag", "signal": "neutral", "confidence": 0.6, "reasoning": "Filing shows stable revenue growth but rising costs", "source_snippet": "revenue grew 14.7% but EBITDA margin narrowed"}'

result = synthesis_agent(fake_momentum, fake_sentiment, fake_rag, "aggressive")
print(result)

import re, json

def clean_json_response(text):
    cleaned = re.sub(r"```json|```", "", text).strip()
    try:
        return json.loads(cleaned)
    except:
        return {"error": "Could not parse", "raw": cleaned}

result_dict = clean_json_response(result)
print(result_dict)