# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6LLyO5kVerXepu0Dn205-maygrOUoe5
"""

import os
!pip install groq

from groq import Groq

# Ensure the API key is loaded securely, e.g., from environment variables
client = Groq(api_key=os.environ.get("GROQ_API_KEY", "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"))

def momentum_agent(stock_name, price_summary):
    prompt = f"""You are a technical analysis agent. Stock: {stock_name}
Price data: {price_summary}

Return ONLY JSON: {{\"agent\": \"momentum\", \"signal\": \"bullish/bearish/neutral\", \"confidence\": 0-1, \"reasoning\": \"1-2 sentences\"}}"""

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b", # Changed model from 'llama2-70b-4096' to 'mixtral-8x7b-32768'
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

print(momentum_agent("Reliance", "Price up 4% over 20 days, above MA20, rising volume"))

def sentiment_agent(stock_name, headlines):
    prompt = f"""You are a news sentiment agent. Stock: {stock_name}
Headlines: {headlines}

Return ONLY JSON: {{"agent": "sentiment", "signal": "bullish/bearish/neutral", "confidence": 0-1, "reasoning": "1-2 sentences"}}"""

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

print(sentiment_agent("Zomato", "Zomato's Blinkit drives strong quarterly revenue growth; Zomato margins narrow as quick commerce expansion accelerates"))